name: test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

env:
  FOUNDRY_PROFILE: ci
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Show Foundry config
        run: forge config

      - name: Run forge tests
        run: forge test -vvv